In [6]:
from keras.models import Sequential #케라스의 모델 도구중 시퀀설 모델
from keras.layers import SimpleRNN, Dense  #레이어도구중 rnn과 덴스 도구 덴스는 각 레이어에서 뉴런의 수
from sklearn.preprocessing import MinMaxScaler  #데이터를 정규화 하기위한 함수
from sklearn.metrics import mean_squared_error   #결과의 정확도를 계산하기 위한 함수
from sklearn.model_selection import train_test_split   #훈련과 검증으로 나누는 함수
import math   #넘피와 그래프와 plt
import numpy as np
import matplotlib.pyplot as plt
from pandas import read_csv     #판다스는 파이썬에서 데이터를 처리할때 유용

In [7]:
!git clone https://github.com/yhlee1627/deeplearning.git
dataframe = read_csv('/content/deeplearning/corona_daily.csv', usecols=[3], engine='python',skipfooter=3)
print(dataframe)
dataset = dataframe.values
dataset = dataset.astype('float32')

fatal: destination path 'deeplearning' already exists and is not an empty directory.
     Confirmed
0           24
1           24
2           27
3           27
4           28
..         ...
107      11190
108      11206
109      11225
110      11265
111      11344

[112 rows x 1 columns]